#define _CRT_SECURE_NO_WARNINGS
/* ===========================================================================
 *  s4p_gen.c -- write a 4-port Touchstone file for a coupled pair of lanes.
 *
 *  WHY THIS EXISTS. The right input to channel_build_from_sparam() is a VNA
 *  sweep or a field-solver export of a real package and backplane. I do not
 *  have one to publish, and shipping a file labelled "measured" that is not
 *  would be worse than shipping none. So this tool SYNTHESISES a file from
 *  first-principles physics, and says so on the first line of every file it
 *  writes.
 *
 *  What it does give you that the fitted loss model cannot:
 *
 *    REFLECTIONS. Two impedance discontinuities -- say a connector and a
 *    package ball -- bounce energy between them. The round trip appears as
 *    ripple in |S21| with a period of 1/(2*td), and in the time domain as an
 *    echo arriving 2*td after the cursor. At 100 GBd a 25 ps segment puts that
 *    echo 5 UI out; a 250 ps one puts it 50 UI out, past the end of any
 *    equaliser. That is the entire reason reflections are dangerous: they are
 *    not attenuated enough to ignore and not close enough to cancel.
 *
 *    A VIA STUB. The unused barrel below a through via is an open shunt stub.
 *    Its input admittance is jY0*tan(2*pi*f*L/v), which goes to infinity at the
 *    quarter-wave frequency and shorts the line: a deep, narrow notch. Put it
 *    near Nyquist and the link cannot be equalised at any power. This is what
 *    back-drilling is for, and it is worth being able to demonstrate.
 *
 *    FEXT. Far-end crosstalk from the neighbouring lane. It rises with
 *    frequency (the coupling is a derivative), so it is worst exactly where
 *    PAM4 keeps its information.
 *
 *  Port map, "chained" convention:
 *      1 = victim near end      2 = victim far end
 *      3 = aggressor near end   4 = aggressor far end
 *  so S21 is the through path and S23 is FEXT into the victim's receiver.
 *
 *  Usage:  s4p_gen [out.s4p] [IL_dB_at_Nyquist] [stub_notch_GHz] [fext_dB]
 * =========================================================================*/
#include "link_config.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#define NPT        801u          /* 0.05 .. 80 GHz, 100 MHz steps */
#define F_START    0.05
#define F_STOP     80.0

typedef struct { double re, im; } cx;

static cx cx_mul(cx a, cx b)
{
    cx r;
    r.re = a.re * b.re - a.im * b.im;
    r.im = a.re * b.im + a.im * b.re;
    return r;
}

static cx cx_add(cx a, cx b)
{
    cx r;
    r.re = a.re + b.re;
    r.im = a.im + b.im;
    return r;
}

static cx cx_scale(cx a, double s)
{
    cx r;
    r.re = a.re * s;
    r.im = a.im * s;
    return r;
}

static cx cx_div(cx a, cx b)
{
    const double d = b.re * b.re + b.im * b.im;
    cx r;
    r.re = (a.re * b.re + a.im * b.im) / d;
    r.im = (a.im * b.re - a.re * b.im) / d;
    return r;
}

/* exp(j*theta) */
static cx cx_expj(double th)
{
    cx r;
    r.re = cos(th);
    r.im = sin(th);
    return r;
}

int main(int argc, char **argv)
{
    const char  *out      = (argc > 1) ? argv[1] : "channel.s4p";
    const double il_db    = (argc > 2) ? atof(argv[2]) : 22.0;
    const double stub_ghz = (argc > 3) ? atof(argv[3]) : 62.0;
    const double fext_db  = (argc > 4) ? atof(argv[4]) : -38.0;

    /* Loss split between skin effect and dielectric, as in channel.c, chosen
     * so the total hits il_db at Nyquist. */
    const double fn      = NYQUIST_GHZ;
    const double a_skin  = SKIN_FRACTION         * il_db / sqrt(fn);
    const double a_diel  = (1.0 - SKIN_FRACTION) * il_db / fn;

    /* Flight time of the whole link and of the segment between the two
     * discontinuities. 420 ps end to end is a short backplane hop; the 55 ps
     * segment is a package-to-connector run, and its round trip lands the echo
     * about 11 UI after the cursor. */
    const double td_total_ns = 0.420;
    const double td_seg_ns   = 0.055;
    const double rho1        = 0.13;   /* connector discontinuity  */
    const double rho2        = 0.10;   /* package ball             */

    /* Quarter-wave open stub placed to notch at stub_ghz. */
    const double f_notch = stub_ghz;

    FILE *fp = fopen(out, "w");
    if (fp == NULL) {
        fprintf(stderr, "cannot write %s\n", out);
        return 1;
    }

    fprintf(fp, "! SYNTHESISED, NOT MEASURED. Generated by apps/s4p_gen.c.\n");
    fprintf(fp, "! Physical model, not a capture of real hardware. Replace this\n");
    fprintf(fp, "! file with a VNA sweep or a field-solver export when you have one;\n");
    fprintf(fp, "! the reader in src/touchstone.c takes either without changes.\n");
    fprintf(fp, "!\n");
    fprintf(fp, "! Coupled lane pair, chained ports:\n");
    fprintf(fp, "!   1 victim near   2 victim far   3 aggressor near   4 aggressor far\n");
    fprintf(fp, "! S21 through, S23 FEXT, S11 return loss.\n");
    fprintf(fp, "!\n");
    fprintf(fp, "! insertion loss   %.1f dB at %.0f GHz (Nyquist)\n", il_db, fn);
    fprintf(fp, "! skin / dielectric %.4f dB/sqrt(GHz) / %.4f dB/GHz\n", a_skin, a_diel);
    fprintf(fp, "! flight time      %.0f ps end to end\n", td_total_ns * 1000.0);
    fprintf(fp, "! discontinuities  rho %.2f and %.2f, %.0f ps apart\n",
            rho1, rho2, td_seg_ns * 1000.0);
    fprintf(fp, "!                  -> echo at %.1f UI after the cursor\n",
            2.0 * td_seg_ns * 1e-9 * BAUD_RATE_GBD * 1e9);
    fprintf(fp, "! via stub         quarter-wave notch at %.0f GHz\n", f_notch);
    fprintf(fp, "! FEXT             %.0f dB at Nyquist, rising with frequency\n", fext_db);
    fprintf(fp, "#  GHZ  S  RI  R  50\n");

    for (unsigned k = 0; k < NPT; ++k) {
        const double f = F_START + (F_STOP - F_START) * (double)k / (double)(NPT - 1u);

        /* ---- lossy line ------------------------------------------------- */
        const double il   = a_skin * sqrt(f) + a_diel * f;      /* dB */
        const double amp  = pow(10.0, -il / 20.0);
        const double thT  = -2.0 * M_PI * f * td_total_ns;      /* rad, f in GHz, td in ns */
        cx line = cx_scale(cx_expj(thT), amp);

        /* ---- via stub: shunt open stub, quarter wave at f_notch ---------- */
        /* Y_stub / Y0 = j*tan(pi/2 * f/f_notch). A shunt admittance Y across a
         * matched line transmits S21 = 2 / (2 + Y/Y0). At f = f_notch the
         * tangent diverges and S21 goes to zero -- the notch. A small loss
         * term keeps it finite, as a real stub is. */
        const double th_s = (M_PI / 2.0) * (f / f_notch);
        const double tn   = tan(th_s);
        cx ystub;
        ystub.re = 0.004 * (1.0 + tn * tn);     /* stub dissipation */
        ystub.im = tn;
        cx den = ystub;
        den.re += 2.0;
        cx two = { 2.0, 0.0 };
        const cx stub = cx_div(two, den);

        /* ---- two discontinuities, multiple reflections ------------------- */
        /* The through path is the direct wave plus every even bounce between
         * the two discontinuities. Summed as a geometric series rather than
         * truncated, so the ripple is exactly periodic in 1/(2*td_seg). */
        const double th_seg = -2.0 * M_PI * f * (2.0 * td_seg_ns);
        const cx bounce = cx_scale(cx_expj(th_seg), rho1 * rho2);
        cx one_minus = { 1.0 - bounce.re, -bounce.im };
        const cx multi = cx_div((cx){ 1.0, 0.0 }, one_minus);

        cx s21 = cx_mul(cx_mul(line, stub), multi);
        s21 = cx_scale(s21, (1.0 - rho1 * rho1) * (1.0 - rho2 * rho2));

        /* ---- return loss ------------------------------------------------ */
        /* First discontinuity directly, plus the second seen through the
         * segment. Enough structure to be realistic; not a full model. */
        cx s11 = { rho1, 0.0 };
        const cx back = cx_scale(cx_expj(th_seg), rho2 * (1.0 - rho1 * rho1));
        s11 = cx_add(s11, back);
        s11 = cx_scale(s11, 1.0);

        /* ---- FEXT ------------------------------------------------------- */
        /* Far-end crosstalk is a coupled-mode derivative: it scales with
         * frequency and carries the same loss and delay as the through path.
         * That frequency dependence is the whole problem -- it is smallest
         * where PAM4 has no information and largest at Nyquist. */
        const double fext_nyq = pow(10.0, fext_db / 20.0);
        const cx fext = cx_scale(cx_expj(thT + M_PI / 2.0),
                                 amp * fext_nyq * (f / fn));

        /* ---- NEXT ------------------------------------------------------- */
        /* Near-end crosstalk saturates instead of rising without bound, and
         * carries no through-path delay. Included for completeness; the
         * receiver model does not currently use it. */
        const cx next = cx_scale(cx_expj(-2.0 * M_PI * f * 0.02),
                                 pow(10.0, -34.0 / 20.0) *
                                 (f / (f + 8.0)));

        /* ---- assemble the 4x4, row major -------------------------------- */
        cx S[4][4];
        for (unsigned a = 0; a < 4u; ++a) {
            for (unsigned b = 0; b < 4u; ++b) {
                S[a][b].re = 0.0;
                S[a][b].im = 0.0;
            }
        }
        S[0][0] = s11;  S[1][1] = s11;  S[2][2] = s11;  S[3][3] = s11;
        S[1][0] = s21;  S[0][1] = s21;                 /* victim through     */
        S[3][2] = s21;  S[2][3] = s21;                 /* aggressor through  */
        S[1][2] = fext; S[2][1] = fext;                /* FEXT into victim   */
        S[3][0] = fext; S[0][3] = fext;
        S[2][0] = next; S[0][2] = next;                /* NEXT               */
        S[3][1] = next; S[1][3] = next;

        /* Touchstone writes n^2 pairs per frequency, conventionally one matrix
         * row per line for n > 2. */
        fprintf(fp, "%.6f", f);
        for (unsigned a = 0; a < 4u; ++a) {
            for (unsigned b = 0; b < 4u; ++b) {
                fprintf(fp, " %+.6e %+.6e", S[a][b].re, S[a][b].im);
            }
            fprintf(fp, "\n");
            if (a < 3u) {
                fprintf(fp, "        ");
            }
        }
    }

    fclose(fp);
    printf("wrote %s : %u points, %.2f to %.1f GHz, 4 ports\n",
           out, NPT, F_START, F_STOP);
    printf("  %.1f dB at Nyquist, via-stub notch at %.0f GHz, FEXT %.0f dB\n",
           il_db, stub_ghz, fext_db);
    printf("  reflection echo lands %.1f UI after the cursor\n",
           2.0 * td_seg_ns * 1e-9 * BAUD_RATE_GBD * 1e9);
    return 0;
}
